In [1]:
import numpy as np

In [4]:
matrix = np.arange(50).reshape(5, 10)

In [5]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [7]:
# Let's grab: 
# [[23, 24, 25],
#  [33, 34, 35],
#  [43, 44, 45]]

matrix[2:5, 3:6]

array([[23, 24, 25],
       [33, 34, 35],
       [43, 44, 45]])

In [12]:
# Let's grab
# [[ 5,  6,  7,  8,  9],
#  [15, 16, 17, 18, 19],
#  [25, 26, 27, 28, 29],
#  [35, 36, 37, 38, 39]]

matrix[0:4, 5:]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])